#:tombi schema.strict = false
[workspace.package]
version = "1.0.0"
edition = "2024"
description = "A GUI application for checking and downloading updates."

[workspace]
resolver = "3"
members = ["ui", "core", "manager-api", "managers"]

[workspace.dependencies]
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"
directories-next = "2"
env_logger = "0.11"
futures = "0.3"
iced = { version = "0.14", default-features = false, features = [
  "advanced",
  "crisp",
  "svg",
  "thread-pool",
  "tiny-skia",
  "tokio",
  "web-colors",
  "wgpu",
] }
log = "0.4"
libc = "0.2"
mimalloc = "0.1"
notify-rust = "4"
regex = "1"
reqwest = { version = "0.13", features = ["json"] }
rfd = "0.17"
roxmltree = "0.20"
semver = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
updater_core = { path = "core" }
updater_manager_api = { package = "updater-manager-api", path = "manager-api" }
updater_managers = { package = "updater-managers", path = "managers" }
url = "2"
unicode-width = "0.2"
winresource = "0.1"

[profile.dev]
opt-level = 1
incremental = true
debug = true
split-debuginfo = "unpacked"

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
incremental = false

[profile.dev.package]
updater_core = { opt-level = 1, incremental = true }
iced = { opt-level = 3}
iced_core = { opt-level = 3 }
iced_widget = { opt-level = 3 }
iced_winit = { opt-level = 3 }
winit = { opt-level = 3 }
tokio = { opt-level = 3 }
serde = { opt-level = 3 }
env_logger = { opt-level = 3 }
log = { opt-level = 3 }
mimalloc = { opt-level = 3 }
futures = { opt-level = 3 }


[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.wasm-release]
# Default to release profile values.
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"
