[package]
name = "updater_core"
version.workspace = true
edition.workspace = true
description.workspace = true

[lib]
name = "updater_core"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
directories-next.workspace = true
env_logger.workspace = true
futures.workspace = true
log.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
updater_manager_api.workspace = true

[dev-dependencies]
tempfile.workspace = true
