[package]
name = "updater_core"
version.workspace = true
edition.workspace = true
description.workspace = true

[lib]
name = "updater_core"
path = "src/lib.rs"

[dependencies]
directories-next.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
updater_manager_api.workspace = true
updater_managers.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
